/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelo.*;
import Persistencia.*;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import static java.lang.System.exit;
import java.sql.Array;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author L. Nudel
 */
public class IniciarSesion extends javax.swing.JPanel {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInicioDeSesion = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenia = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPasswordFieldPass = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(400, 400));

        jLabelInicioDeSesion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelInicioDeSesion.setText("Inicio de Sesion");

        jLabelUsuario.setText("Usuario: ");

        jLabelContrasenia.setText("Contraseña: ");

        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyTyped(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabelInicioDeSesion))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUsuario)
                                    .addComponent(jLabelContrasenia))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUsuario)
                                    .addComponent(jPasswordFieldPass))))
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButtonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInicioDeSesion)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrasenia)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        String usuario = this.jTextFieldUsuario.getText();
        String pass = "";
        char [] password = this.jPasswordFieldPass.getPassword();
        for(int i=0; i<password.length;i++){
            pass+=password[i];
        }
        BedelDAO BDAO = new BedelDAO();
        ClaveDao CDAO = new ClaveDao();
        AdministradorDAO ADAO = new AdministradorDAO();
        //Verificar limite de caracteres en ambos campos
        if(usuario.length()>5 && usuario.length()<33 ){
            if( pass.length()>5 && pass.length()<33){
                //verifico si el bedel existe
                if(BDAO.verificarExistencia(usuario)){
                    Bedel b = BDAO.obtenerBedel(usuario);
                    //obtengo el ultimo elemento del hashset
                    ClaveBedel cb=null;
                    ClaveBedel cAnterior=null;
                    //busco la contraseña mas actual
                    
                    for(ClaveBedel c: b.getClaveBedels()){
                        if(cb==null){
                            cb=c;
                            cAnterior=c;        
                        }else{
                            if(c.getId().getFecha().compareTo(cAnterior.getId().getFecha())>0){
                                cb=c;
                                cAnterior=c;
                            }else cAnterior=c;
                        }
                        
                    }
                    //verifico si la clave concuerda
                    if(cb.getId().getValor().equals(pass) && cb.getId().getBedelUsername().equals(b.getUsername())){
                        //ir al menu de bedel
                        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
                        menuPrincipalBedel menuBedel = new menuPrincipalBedel();
                        topFrame.add(menuBedel, BorderLayout.CENTER);
                        this.setVisible(false);
                        topFrame.remove(this);
                        topFrame.setSize(500,500);
                        
                    }else{
                        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
                        topFrame.mensajeEmergente("Error", "La contraseña es invalida");
                    }
                    
                    
                   
                }else{
                    //verifico si el admin existe
                    if(ADAO.verificarExistencia(usuario)){
                        Administrador a = ADAO.obtenerAdministrador(usuario);
                        //obtengo el ultimo elemento del hashset
                        ClaveAdministrador ca=null;
                        ClaveAdministrador cAnt=null;
                        for(ClaveAdministrador c: a.getClaveAdministradors()){
                        if(ca==null){
                            ca=c;
                            cAnt=c;        
                        }else{
                            if(c.getId().getFecha().compareTo(cAnt.getId().getFecha())>0){
                                ca=c;
                                cAnt=c;
                            }else cAnt=c;
                        }
                        
                    }
                        //verifico si la clave concuerda
                        
                        if(ca.getId().getValor().equals(pass) && ca.getId().getAdministradorUsername().equals(a.getUsername())){
                        //ir al menu de admin
                        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
                        MenuPrincipalAdmin menuAdmin = new MenuPrincipalAdmin();
                        topFrame.add(menuAdmin, BorderLayout.CENTER);
                        this.setVisible(false);
                        topFrame.remove(this);
                        topFrame.setSize(500,500);
                        
                        
                        
                        
                    }else{
                        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
                        topFrame.mensajeEmergente("Error", "La contraseña es invalida");
                    }
                        
                        
                        
                    }else{
                        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
                        topFrame.mensajeEmergente("Error", "El usuario no existe");
                    }
                    
                }
                
                
                
                
            }else{
                JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
                topFrame.mensajeEmergente("Error", "Los numeros de caracteres para el campo contraseña estan fuera del limite");
                //limpia el campo contraseña
                this.jPasswordFieldPass.setText(null);
            }
            
        }else{
            JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
            topFrame.mensajeEmergente("Error", "Los numeros de caracteres para el campo usuario estan fuera del limite");
            //limpia el campo usuario
            this.jTextFieldUsuario.setText(null);
        
        
        }
        
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
        ArrayList<JButton> botonesDialogo = new ArrayList<>();
        botonesDialogo = topFrame.mensajeEmergenteConfirmacion("Confirmación de cierre", "¿Está seguro de querer salir del programa?");
        JDialog dialogo = (JDialog) SwingUtilities.getWindowAncestor(botonesDialogo.get(0));
        
        botonesDialogo.get(0).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
            exit(0);             
        });
        
        botonesDialogo.get(1).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
        });
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldUsuarioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelInicioDeSesion;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
