/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import static java.lang.System.exit;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author L. Nudel
 */
public class MenuPrincipalBedel extends javax.swing.JPanel {

    /**
     * Creates new form menuPrincipalBedel
     */
    public MenuPrincipalBedel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelMenuPrincipal = new javax.swing.JLabel();
        jLabelNuevaReserva = new javax.swing.JLabel();
        jLabelBuscarAula = new javax.swing.JLabel();
        jLabelListadoDeReservas = new javax.swing.JLabel();
        jLabelListadoDeReservasDia = new javax.swing.JLabel();
        jLabelListadoDeReservasCurso = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonNuevaReserva = new javax.swing.JButton();
        jToggleButtonBuscarAula = new javax.swing.JToggleButton();
        jToggleButtonListadoDeReservas = new javax.swing.JToggleButton();
        jToggleButtonListadoDeReservasDia = new javax.swing.JToggleButton();
        jToggleButtonListadoDeReservasCurso = new javax.swing.JToggleButton();

        jButton1.setText("jButton1");

        jLabelMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMenuPrincipal.setText("Menu Principal");

        jLabelNuevaReserva.setText("Nueva reserva");

        jLabelBuscarAula.setText("Buscar Aula");

        jLabelListadoDeReservas.setText("Listado de reservas");

        jLabelListadoDeReservasDia.setText("Listado de reservas (dia)");

        jLabelListadoDeReservasCurso.setText("Listado de reservas (curso)");

        jButtonSalir.setText("Cerrar sesión");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonNuevaReserva.setText(">");

        jToggleButtonBuscarAula.setText(">");

        jToggleButtonListadoDeReservas.setText(">");

        jToggleButtonListadoDeReservasDia.setText(">");

        jToggleButtonListadoDeReservasCurso.setText(">");
        jToggleButtonListadoDeReservasCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonListadoDeReservasCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBuscarAula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonBuscarAula))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNuevaReserva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonNuevaReserva))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelListadoDeReservasCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonListadoDeReservasCurso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelListadoDeReservas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonListadoDeReservas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelListadoDeReservasDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonListadoDeReservasDia))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabelMenuPrincipal)
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabelMenuPrincipal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNuevaReserva)
                    .addComponent(jButtonNuevaReserva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscarAula)
                    .addComponent(jToggleButtonBuscarAula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelListadoDeReservas)
                    .addComponent(jToggleButtonListadoDeReservas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListadoDeReservasDia)
                    .addComponent(jToggleButtonListadoDeReservasDia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListadoDeReservasCurso)
                    .addComponent(jToggleButtonListadoDeReservasCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
         JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
        ArrayList<JButton> botonesDialogo = new ArrayList<>();
        botonesDialogo = topFrame.mensajeEmergenteConfirmacion("Confirmación de cierre", "¿Está seguro de querer cerrar la sesión?");
        JDialog dialogo = (JDialog) SwingUtilities.getWindowAncestor(botonesDialogo.get(0));
        
        botonesDialogo.get(0).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
            IniciarSesion panelInicio = new IniciarSesion();
            topFrame.add(panelInicio, BorderLayout.CENTER);
            this.setVisible(false);
            topFrame.remove(this);
            topFrame.setSize(500,500);              
        });
        
        botonesDialogo.get(1).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
        });
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jToggleButtonListadoDeReservasCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonListadoDeReservasCursoActionPerformed
        // TODO add your handling code here:
        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
        ListaDeReservaParaCurso listaRC = new ListaDeReservaParaCurso();
        topFrame.add(listaRC, BorderLayout.CENTER);
        this.setVisible(false);
        topFrame.remove(this);
        topFrame.setSize(600,600);
    }//GEN-LAST:event_jToggleButtonListadoDeReservasCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonNuevaReserva;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBuscarAula;
    private javax.swing.JLabel jLabelListadoDeReservas;
    private javax.swing.JLabel jLabelListadoDeReservasCurso;
    private javax.swing.JLabel jLabelListadoDeReservasDia;
    private javax.swing.JLabel jLabelMenuPrincipal;
    private javax.swing.JLabel jLabelNuevaReserva;
    private javax.swing.JToggleButton jToggleButtonBuscarAula;
    private javax.swing.JToggleButton jToggleButtonListadoDeReservas;
    private javax.swing.JToggleButton jToggleButtonListadoDeReservasCurso;
    private javax.swing.JToggleButton jToggleButtonListadoDeReservasDia;
    // End of variables declaration//GEN-END:variables
}
