/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author L. Nudel
 */
public class menuPrincipalBedel extends javax.swing.JPanel {

    /**
     * Creates new form menuPrincipalBedel
     */
    public menuPrincipalBedel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelMenuPrincipal = new javax.swing.JLabel();
        jLabelNuevaReserva = new javax.swing.JLabel();
        jLabelBuscarAula = new javax.swing.JLabel();
        jLabelListadoDeReservas = new javax.swing.JLabel();
        jLabelListadoDeReservasDia = new javax.swing.JLabel();
        jLabelListadoDeReservasCurso = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonNuevaReserva = new javax.swing.JButton();
        jToggleButtonBuscarAula = new javax.swing.JToggleButton();
        jToggleButtonListadoDeReservas = new javax.swing.JToggleButton();
        jToggleButtonListadoDeReservasDia = new javax.swing.JToggleButton();
        jToggleButtonListadoDeReservasCurso = new javax.swing.JToggleButton();

        jButton1.setText("jButton1");

        jLabelMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMenuPrincipal.setText("Menu Principal");

        jLabelNuevaReserva.setText("Nueva reserva");

        jLabelBuscarAula.setText("Buscar Aula");

        jLabelListadoDeReservas.setText("Listado de reservas");

        jLabelListadoDeReservasDia.setText("Listado de reservas (dia)");

        jLabelListadoDeReservasCurso.setText("Listado de reservas (curso)");

        jButtonSalir.setText("Salir");

        jButtonAtras.setText("Atras");

        jButtonNuevaReserva.setText(">");

        jToggleButtonBuscarAula.setText(">");

        jToggleButtonListadoDeReservas.setText(">");

        jToggleButtonListadoDeReservasDia.setText(">");

        jToggleButtonListadoDeReservasCurso.setText(">");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelBuscarAula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonBuscarAula))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNuevaReserva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonNuevaReserva))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelListadoDeReservasCurso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonListadoDeReservasCurso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelListadoDeReservas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonListadoDeReservas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelListadoDeReservasDia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonListadoDeReservasDia))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonAtras))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabelMenuPrincipal)))
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSalir)
                .addGap(18, 18, 18)
                .addComponent(jLabelMenuPrincipal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNuevaReserva)
                    .addComponent(jButtonNuevaReserva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuscarAula)
                    .addComponent(jToggleButtonBuscarAula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelListadoDeReservas)
                    .addComponent(jToggleButtonListadoDeReservas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListadoDeReservasDia)
                    .addComponent(jToggleButtonListadoDeReservasDia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelListadoDeReservasCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jButtonAtras))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonListadoDeReservasCurso)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonNuevaReserva;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBuscarAula;
    private javax.swing.JLabel jLabelListadoDeReservas;
    private javax.swing.JLabel jLabelListadoDeReservasCurso;
    private javax.swing.JLabel jLabelListadoDeReservasDia;
    private javax.swing.JLabel jLabelMenuPrincipal;
    private javax.swing.JLabel jLabelNuevaReserva;
    private javax.swing.JToggleButton jToggleButtonBuscarAula;
    private javax.swing.JToggleButton jToggleButtonListadoDeReservas;
    private javax.swing.JToggleButton jToggleButtonListadoDeReservasCurso;
    private javax.swing.JToggleButton jToggleButtonListadoDeReservasDia;
    // End of variables declaration//GEN-END:variables
}
