/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelo.PeriodoEnum;
import Modelo.TipoAula;
import Modelo.TipoReserva;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Temp
 */
public class RegistrarReserva extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarReserva
     */
    public RegistrarReserva() {
        initComponents();
        
        /*String path = "/Imagenes/iconoaula1.png";  
        URL url = this.getClass().getResource(path);  
        ImageIcon icon = new ImageIcon(url);
        jLabel2.setIcon(icon); */ 
            
            listaPeriodo.setVisible(false);
            listaCuatrimestre.setVisible(false);
            jLabelDiaSemana.setVisible(false);
            jCheckBoxLunes.setVisible(false);
            jCheckBoxMartes.setVisible(false);
            jCheckBoxMiercoles.setVisible(false);
            jCheckBoxJueves.setVisible(false);
            jCheckBoxViernes.setVisible(false);
            jCheckBoxSabado.setVisible(false);
            jLabelDuracion1.setVisible(false);
            duracionLunes.setVisible(false);
            duracionMartes.setVisible(false);
            duracionMiercoles.setVisible(false);
            duracionJueves.setVisible(false);
            duracionViernes.setVisible(false);
            duracionSabado.setVisible(false);
            jLabelHoraInicio1.setVisible(false);
            horaInicioLunes.setVisible(false);
            horaInicioMartes.setVisible(false);
            horaInicioMiercoles.setVisible(false);
            horaInicioJueves.setVisible(false);
            horaInicioViernes.setVisible(false);
            horaInicioSabado.setVisible(false);
            
            jLabelFecha.setVisible(true);
            fecha.setVisible(true);
            jLabelHoraInicio2.setVisible(true);
            horaInicio.setVisible(true);
            jLabelDuracion2.setVisible(true);
            duracion.setVisible(true);
            tabla.setVisible(true);
            panelTabla.setVisible(true);
            jButtonEliminar.setVisible(true);
            jButtonAnadir.setVisible(true);
            
            /*JTableHeader header= tabla.getTableHeader();
            TableColumnModel colMod = header.getColumnModel();
            colMod.getColumn(0).setHeaderValue("Fecha");
            colMod.getColumn(1).setHeaderValue("Hora inicio");
            colMod.getColumn(2).setHeaderValue("Duracion");
            header.repaint();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipoAula = new javax.swing.JComboBox<>();
        cantidadAlumnos = new javax.swing.JTextField();
        listaModalidad = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelFecha = new javax.swing.JLabel();
        jLabelHoraInicio2 = new javax.swing.JLabel();
        jLabelDuracion2 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        horaInicio = new javax.swing.JTextField();
        duracion = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAnadir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        catedra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        atras = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabelDiaSemana = new javax.swing.JLabel();
        jCheckBoxLunes = new javax.swing.JCheckBox();
        jCheckBoxMartes = new javax.swing.JCheckBox();
        jCheckBoxMiercoles = new javax.swing.JCheckBox();
        jCheckBoxJueves = new javax.swing.JCheckBox();
        jCheckBoxViernes = new javax.swing.JCheckBox();
        jCheckBoxSabado = new javax.swing.JCheckBox();
        jLabelHoraInicio1 = new javax.swing.JLabel();
        horaInicioLunes = new javax.swing.JTextField();
        horaInicioMartes = new javax.swing.JTextField();
        horaInicioMiercoles = new javax.swing.JTextField();
        horaInicioJueves = new javax.swing.JTextField();
        horaInicioViernes = new javax.swing.JTextField();
        horaInicioSabado = new javax.swing.JTextField();
        jLabelDuracion1 = new javax.swing.JLabel();
        duracionLunes = new javax.swing.JComboBox<>();
        duracionMartes = new javax.swing.JComboBox<>();
        duracionMiercoles = new javax.swing.JComboBox<>();
        duracionJueves = new javax.swing.JComboBox<>();
        duracionViernes = new javax.swing.JComboBox<>();
        duracionSabado = new javax.swing.JComboBox<>();
        listaPeriodo = new javax.swing.JComboBox<>();
        listaCuatrimestre = new javax.swing.JComboBox<>();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar reserva");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de aula:");
        jLabel3.setToolTipText("Elija una modalidad de la lista.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de alumnos:");
        jLabel4.setToolTipText("Cantidad mínima: 1 - Cantidad máxima: 250");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modalidad:");
        jLabel5.setToolTipText("Elija una modalidad de la lista.");

        tipoAula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula multimedio", "Aula informatica", "Aula sin recursos adicionales" }));
        tipoAula.setToolTipText("Elija una modalidad de la lista.");
        tipoAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAulaActionPerformed(evt);
            }
        });

        cantidadAlumnos.setToolTipText("Cantidad mínima: 1 - Cantidad máxima: 250");

        listaModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esporadica", "Periodica" }));
        listaModalidad.setToolTipText("Elija una modalidad de la lista.");
        listaModalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaModalidadActionPerformed(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha:");

        jLabelHoraInicio2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHoraInicio2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraInicio2.setText("Hora de inicio:");

        jLabelDuracion2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDuracion2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDuracion2.setText("Duración:");

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar de la lista");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonAnadir.setText("Añadir a la lista");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cátedra:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Apellido:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("E-mail:");

        atras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atras.setText("Cancelar");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        aceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aceptar.setText("Obtener aulas disponibles");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabelDiaSemana.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDiaSemana.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDiaSemana.setText("Día de la semana:");

        jCheckBoxLunes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxLunes.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxLunes.setText("Lunes");

        jCheckBoxMartes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxMartes.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMartes.setText("Martes");

        jCheckBoxMiercoles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxMiercoles.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMiercoles.setText("Miércoles");

        jCheckBoxJueves.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxJueves.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxJueves.setText("Jueves");

        jCheckBoxViernes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxViernes.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxViernes.setText("Viernes");

        jCheckBoxSabado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxSabado.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxSabado.setText("Sábado");
        jCheckBoxSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSabadoActionPerformed(evt);
            }
        });

        jLabelHoraInicio1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHoraInicio1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraInicio1.setText("Hora de inicio:");

        horaInicioMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaInicioMartesActionPerformed(evt);
            }
        });

        horaInicioSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaInicioSabadoActionPerformed(evt);
            }
        });

        jLabelDuracion1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDuracion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDuracion1.setText("Duración:");

        duracionLunes.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        duracionLunes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 min", "60 min", "90 min", "120 min", "150 min", "180 min", "210 min", "240 min", "270 min", "300 min", "330 min", "360 min" }));
        duracionLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionLunesActionPerformed(evt);
            }
        });

        duracionMartes.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        duracionMartes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 min", "60 min", "90 min", "120 min", "150 min", "180 min", "210 min", "240 min", "270 min", "300 min", "330 min", "360 min" }));

        duracionMiercoles.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        duracionMiercoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 min", "60 min", "90 min", "120 min", "150 min", "180 min", "210 min", "240 min", "270 min", "300 min", "330 min", "360 min" }));

        duracionJueves.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        duracionJueves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 min", "60 min", "90 min", "120 min", "150 min", "180 min", "210 min", "240 min", "270 min", "300 min", "330 min", "360 min" }));

        duracionViernes.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        duracionViernes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 min", "60 min", "90 min", "120 min", "150 min", "180 min", "210 min", "240 min", "270 min", "300 min", "330 min", "360 min" }));

        duracionSabado.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        duracionSabado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30 min", "60 min", "90 min", "120 min", "150 min", "180 min", "210 min", "240 min", "270 min", "300 min", "330 min", "360 min" }));

        listaPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuatrimestral", "Anual" }));
        listaPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPeriodoActionPerformed(evt);
            }
        });

        listaCuatrimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º", "2º" }));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Hora inicio", "Duración"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout panelTablaLayout = new javax.swing.GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(listaModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(listaPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(listaCuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tipoAula, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(12, 12, 12)
                                .addComponent(cantidadAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDiaSemana)
                            .addComponent(jLabelHoraInicio1)
                            .addComponent(jLabelDuracion1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxLunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(horaInicioLunes)
                            .addComponent(duracionLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCheckBoxMartes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(horaInicioMartes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(duracionMartes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBoxMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(horaInicioMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBoxJueves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(horaInicioJueves, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBoxViernes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(horaInicioViernes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBoxSabado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(horaInicioSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(duracionMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(duracionJueves, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(duracionViernes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(duracionSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFecha)
                        .addGap(18, 18, 18)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHoraInicio2)
                        .addGap(18, 18, 18)
                        .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelDuracion2)
                        .addGap(18, 18, 18)
                        .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(16, 16, 16)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(catedra, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atras))
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(aceptar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cantidadAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(listaPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaCuatrimestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiaSemana)
                    .addComponent(jCheckBoxLunes)
                    .addComponent(jCheckBoxMartes)
                    .addComponent(jCheckBoxMiercoles)
                    .addComponent(jCheckBoxJueves)
                    .addComponent(jCheckBoxViernes)
                    .addComponent(jCheckBoxSabado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraInicio1)
                    .addComponent(horaInicioLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaInicioMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaInicioMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaInicioJueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaInicioViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaInicioSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDuracion1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(duracionLunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracionMartes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracionMiercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracionJueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracionViernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracionSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoraInicio2)
                    .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDuracion2)
                    .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(panelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnadir)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(catedra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptar)
                    .addComponent(atras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jCheckBoxSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSabadoActionPerformed

    private void duracionLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionLunesActionPerformed

    private void horaInicioSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaInicioSabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaInicioSabadoActionPerformed

    private void horaInicioMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaInicioMartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaInicioMartesActionPerformed

    private void listaModalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaModalidadActionPerformed
        // TODO add your handling code here:
        String modalidad = listaModalidad.getSelectedItem().toString();
        if (modalidad.equals("Esporadica")){
            listaPeriodo.setVisible(false);
            listaCuatrimestre.setVisible(false);
            jLabelDiaSemana.setVisible(false);
            jCheckBoxLunes.setVisible(false);
            jCheckBoxMartes.setVisible(false);
            jCheckBoxMiercoles.setVisible(false);
            jCheckBoxJueves.setVisible(false);
            jCheckBoxViernes.setVisible(false);
            jCheckBoxSabado.setVisible(false);
            jLabelDuracion1.setVisible(false);
            duracionLunes.setVisible(false);
            duracionMartes.setVisible(false);
            duracionMiercoles.setVisible(false);
            duracionJueves.setVisible(false);
            duracionViernes.setVisible(false);
            duracionSabado.setVisible(false);
            jLabelHoraInicio1.setVisible(false);
            horaInicioLunes.setVisible(false);
            horaInicioMartes.setVisible(false);
            horaInicioMiercoles.setVisible(false);
            horaInicioJueves.setVisible(false);
            horaInicioViernes.setVisible(false);
            horaInicioSabado.setVisible(false);
            
            jLabelFecha.setVisible(true);
            fecha.setVisible(true);
            jLabelHoraInicio2.setVisible(true);
            horaInicio.setVisible(true);
            jLabelDuracion2.setVisible(true);
            duracion.setVisible(true);
            tabla.setVisible(true);
            panelTabla.setVisible(true);
            jButtonEliminar.setVisible(true);
            jButtonAnadir.setVisible(true);
            
            /*JTableHeader header= tabla.getTableHeader();
            TableColumnModel colMod = header.getColumnModel();
            colMod.getColumn(0).setHeaderValue("Fecha");
            colMod.getColumn(1).setHeaderValue("Hora inicio");
            colMod.getColumn(2).setHeaderValue("Duracion");
            header.repaint();*/
        }else{
            jLabelFecha.setVisible(false);
            fecha.setVisible(false);
            jLabelHoraInicio2.setVisible(false);
            horaInicio.setVisible(false);
            jLabelDuracion2.setVisible(false);
            duracion.setVisible(false);
            tabla.setVisible(false);
            panelTabla.setVisible(false);
            jButtonEliminar.setVisible(false);
            jButtonAnadir.setVisible(false);
            
            /*JTableHeader header= tabla.getTableHeader();
            TableColumnModel colMod = header.getColumnModel();
            colMod.getColumn(0).setHeaderValue("");
            colMod.getColumn(1).setHeaderValue("");
            colMod.getColumn(2).setHeaderValue("");
            header.repaint();*/
            
            listaPeriodo.setVisible(true);
            listaCuatrimestre.setVisible(true);
            jLabelDiaSemana.setVisible(true);
            jCheckBoxLunes.setVisible(true);
            jCheckBoxMartes.setVisible(true);
            jCheckBoxMiercoles.setVisible(true);
            jCheckBoxJueves.setVisible(true);
            jCheckBoxViernes.setVisible(true);
            jCheckBoxSabado.setVisible(true);
            jLabelDuracion1.setVisible(true);
            duracionLunes.setVisible(true);
            duracionMartes.setVisible(true);
            duracionMiercoles.setVisible(true);
            duracionJueves.setVisible(true);
            duracionViernes.setVisible(true);
            duracionSabado.setVisible(true);
            jLabelHoraInicio1.setVisible(true);
            horaInicioLunes.setVisible(true);
            horaInicioMartes.setVisible(true);
            horaInicioMiercoles.setVisible(true);
            horaInicioJueves.setVisible(true);
            horaInicioViernes.setVisible(true);
            horaInicioSabado.setVisible(true);
        }
    }//GEN-LAST:event_listaModalidadActionPerformed

    private void listaPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPeriodoActionPerformed
        // TODO add your handling code here:
        String periodo = listaPeriodo.getSelectedItem().toString();
        if(periodo.equals("Cuatrimestral")){
           listaCuatrimestre.setVisible(true);
        }else{
           listaCuatrimestre.setVisible(false);
        }
    }//GEN-LAST:event_listaPeriodoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
        ReservaAulasDisponibles panelAulas = new ReservaAulasDisponibles();
        panelAulas.setImage("/Imagenes/fondoabs.jpg");
        topFrame.add(panelAulas, BorderLayout.CENTER);
        this.setVisible(false);
        topFrame.remove(this);
        topFrame.setSize(1100,500);
        //Recupero...
        //Tipo Aula
        TipoAula tipoAula = TipoAula.SinRecursos;
        switch (this.tipoAula.getSelectedItem().toString()){
           case "Aula informatica": tipoAula = TipoAula.Informatica;break;
           case "Aula multimedio": tipoAula = TipoAula.Multimedios;break;
           case "Aula sin recursos adicionales": tipoAula = TipoAula.SinRecursos;break;
        }
        //cantidad de alumnos
        //Obtengo un String del jTextField, el replaceAll elimina los espacios (si los tuviera) y parseInt lo convierte en int
        int cantAlumnos = Integer.parseInt((this.cantidadAlumnos.getText()).replaceAll(" ", ""));
        //Modalidad
        String modalidad = this.listaModalidad.getSelectedItem().toString();
        if(modalidad.equals("Periodica")){
            TipoReserva tipoReserva = TipoReserva.Periodica;
            //Periodo
            PeriodoEnum periodo;
            //Cuatrimestre (si no esta vacio)
            if (this.listaPeriodo.getSelectedItem().toString().equals("Cuatrimestral")){
                switch (this.listaCuatrimestre.getSelectedItem().toString()){
                    case "1º": periodo = PeriodoEnum.PrimerCuatrimestre;break;
                    case "2º": periodo = PeriodoEnum.SegundoCuatrimestre;break;
                }
            }else{
                periodo = PeriodoEnum.Anual;
            }
            //Dias
            /*ArrayList<Date> dias = new ArrayList();
            if (this.jCheckBoxLunes.isSelected()){
                dias.add(convertirStringADate("Lunes"));
            }
            if (this.jCheckBoxMartes.isSelected()){
                dias.add("Martes");
            }
            if (this.jCheckBoxMiercoles.isSelected()){
                dias.add("Miercoles");
            }
            if (this.jCheckBoxJueves.isSelected()){
                dias.add("Jueves");
            }
            if (this.jCheckBoxViernes.isSelected()){
                dias.add("Viernes");
            }
            if (this.jCheckBoxSabado.isSelected()){
                dias.add("Sabado");
            }*/
            ArrayList<Date> horaInicio = new ArrayList();
            
            ArrayList<Date> horaFin = new ArrayList();
            
            
        }else{  //Si no es periodica es esporádica (no hay otra alternativa)
            TipoReserva tipoReserva = TipoReserva.Esporadica;
            
        }
        String docenteApellido = this.apellido.getText();
        String docenteNombre = this.nombre.getText();
        String email = this.email.getText();
        String catedra = this.catedra.getText();
        
        
       
        
        
        
        
    }//GEN-LAST:event_aceptarActionPerformed
/*
    private Date convertirStringADate(String fecha){
        Date date = null;
        try {
            date = new SimpleDateFormat(format).parse(inputDate);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        return new SimpleDateFormat("EEEE", Locale.ENGLISH).format(date);
        
    }*/
    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        
        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
        
        ArrayList<JButton> botonesDialogo = new ArrayList<>();
        botonesDialogo = topFrame.mensajeEmergenteConfirmacion("Mensaje de Confirmación", "Al regresar al menú principal, los datos que haya ingresado en algún campo serán descartados.");
        JDialog dialogo = (JDialog) SwingUtilities.getWindowAncestor(botonesDialogo.get(0));
        
        botonesDialogo.get(0).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
            MenuPrincipalBedel panelMenu = new MenuPrincipalBedel();
            topFrame.add(panelMenu, BorderLayout.CENTER);
            this.setVisible(false);
            topFrame.remove(this);
            topFrame.setSize(500,500);             
        });
        
        botonesDialogo.get(1).addActionListener((ActionEvent e) -> {
            dialogo.setVisible(false);
            this.remove(dialogo);
        });
    }//GEN-LAST:event_atrasActionPerformed

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
        
        /*Obtengo la duracion*/
        int duracion = Integer.parseInt(this.duracion.getText());
        /*Obtengo la fecha (el try-catch lo tuve que poner porque sino no me compilaba)*/
        String textoFecha = this.fecha.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fecha = null;
        try {
            fecha = sdf.parse(textoFecha);
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*Obtengo la horaInicio*/
        SimpleDateFormat sdfhora = new SimpleDateFormat("hh:mm");
        String textoHora = this.horaInicio.getText();
        Date horaInicio = null;
        try {
            horaInicio = sdfhora.parse(textoHora);
        } catch (ParseException ex) {
            Logger.getLogger(RegistrarReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Object row[] = {fecha,horaInicio,duracion};   
        /*Recupero el modelo de la tabla y agrego las filas a la tabla*/
        ((DefaultTableModel)this.tabla.getModel()).addRow(row);
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    private void tipoAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoAulaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int row = this.tabla.getSelectedRow(); //fila seleccionada
        if(row > 0){
            JFramePrincipal topFrame = (JFramePrincipal) SwingUtilities.getWindowAncestor(this);
            DefaultTableModel modelo = (DefaultTableModel)tabla.getModel(); 
            modelo.removeRow(row); 
       }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    //codigo de la imagen de fondo ----------------------------------------
    private Image fondo=null;
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(fondo,0,0,getWidth(),getHeight(),null);
    }
    
    public void setImage(String image){
        if (image!=null) {
            fondo=new ImageIcon(getClass().getResource(image)).getImage();
        }
    }
    //-----------------------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton atras;
    private javax.swing.JTextField cantidadAlumnos;
    private javax.swing.JTextField catedra;
    private javax.swing.JTextField duracion;
    private javax.swing.JComboBox<String> duracionJueves;
    private javax.swing.JComboBox<String> duracionLunes;
    private javax.swing.JComboBox<String> duracionMartes;
    private javax.swing.JComboBox<String> duracionMiercoles;
    private javax.swing.JComboBox<String> duracionSabado;
    private javax.swing.JComboBox<String> duracionViernes;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField horaInicio;
    private javax.swing.JTextField horaInicioJueves;
    private javax.swing.JTextField horaInicioLunes;
    private javax.swing.JTextField horaInicioMartes;
    private javax.swing.JTextField horaInicioMiercoles;
    private javax.swing.JTextField horaInicioSabado;
    private javax.swing.JTextField horaInicioViernes;
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JCheckBox jCheckBoxJueves;
    private javax.swing.JCheckBox jCheckBoxLunes;
    private javax.swing.JCheckBox jCheckBoxMartes;
    private javax.swing.JCheckBox jCheckBoxMiercoles;
    private javax.swing.JCheckBox jCheckBoxSabado;
    private javax.swing.JCheckBox jCheckBoxViernes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDiaSemana;
    private javax.swing.JLabel jLabelDuracion1;
    private javax.swing.JLabel jLabelDuracion2;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelHoraInicio1;
    private javax.swing.JLabel jLabelHoraInicio2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> listaCuatrimestre;
    private javax.swing.JComboBox<String> listaModalidad;
    private javax.swing.JComboBox<String> listaPeriodo;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipoAula;
    // End of variables declaration//GEN-END:variables
}
