package Modelo;
// Generated 27/10/2017 22:11:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ActividadUniversitaria generated by hbm2java
 */
public class ActividadUniversitaria  implements java.io.Serializable {


     private Integer idActividad;
     private String nombre;
     private String descripcion;
     private String tipo;
     private int duracion;
     private Set docentes = new HashSet(0);
     private Set reservaEsporadicas = new HashSet(0);
     private Set reservaPeriodicas = new HashSet(0);

    public ActividadUniversitaria() {
    }

	
    public ActividadUniversitaria(String nombre, String tipo, int duracion) {
        this.nombre = nombre;
        this.tipo = tipo;
        this.duracion = duracion;
    }
    public ActividadUniversitaria(String nombre, String descripcion, String tipo, int duracion, Set docentes, Set reservaEsporadicas, Set reservaPeriodicas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.duracion = duracion;
       this.docentes = docentes;
       this.reservaEsporadicas = reservaEsporadicas;
       this.reservaPeriodicas = reservaPeriodicas;
    }
   
    public Integer getIdActividad() {
        return this.idActividad;
    }
    
    public void setIdActividad(Integer idActividad) {
        this.idActividad = idActividad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }
    public Set getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Set docentes) {
        this.docentes = docentes;
    }
    public Set getReservaEsporadicas() {
        return this.reservaEsporadicas;
    }
    
    public void setReservaEsporadicas(Set reservaEsporadicas) {
        this.reservaEsporadicas = reservaEsporadicas;
    }
    public Set getReservaPeriodicas() {
        return this.reservaPeriodicas;
    }
    
    public void setReservaPeriodicas(Set reservaPeriodicas) {
        this.reservaPeriodicas = reservaPeriodicas;
    }




}


