package Modelo;
// Generated 26/10/2017 14:37:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private int numeroAula;
     private Integer piso;
     private Byte activo;
     private Integer capacidad;
     private Byte aireAcondicionado;
     private Byte tipoPizarron;
     private AulaSinRecursosAdicionales aulaSinRecursosAdicionales;
     private AulaMultimedio aulaMultimedio;
     private Set diaReservaPeriodicas = new HashSet(0);
     private AulaInformatica aulaInformatica;
     private Set diaReservaEsporadicas = new HashSet(0);

    public Aula() {
    }

	
    public Aula(int numeroAula) {
        this.numeroAula = numeroAula;
    }
    public Aula(int numeroAula, Integer piso, Byte activo, Integer capacidad, Byte aireAcondicionado, Byte tipoPizarron, AulaSinRecursosAdicionales aulaSinRecursosAdicionales, AulaMultimedio aulaMultimedio, Set diaReservaPeriodicas, AulaInformatica aulaInformatica, Set diaReservaEsporadicas) {
       this.numeroAula = numeroAula;
       this.piso = piso;
       this.activo = activo;
       this.capacidad = capacidad;
       this.aireAcondicionado = aireAcondicionado;
       this.tipoPizarron = tipoPizarron;
       this.aulaSinRecursosAdicionales = aulaSinRecursosAdicionales;
       this.aulaMultimedio = aulaMultimedio;
       this.diaReservaPeriodicas = diaReservaPeriodicas;
       this.aulaInformatica = aulaInformatica;
       this.diaReservaEsporadicas = diaReservaEsporadicas;
    }
   
    public int getNumeroAula() {
        return this.numeroAula;
    }
    
    public void setNumeroAula(int numeroAula) {
        this.numeroAula = numeroAula;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public Byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(Byte activo) {
        this.activo = activo;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Byte getAireAcondicionado() {
        return this.aireAcondicionado;
    }
    
    public void setAireAcondicionado(Byte aireAcondicionado) {
        this.aireAcondicionado = aireAcondicionado;
    }
    public Byte getTipoPizarron() {
        return this.tipoPizarron;
    }
    
    public void setTipoPizarron(Byte tipoPizarron) {
        this.tipoPizarron = tipoPizarron;
    }
    public AulaSinRecursosAdicionales getAulaSinRecursosAdicionales() {
        return this.aulaSinRecursosAdicionales;
    }
    
    public void setAulaSinRecursosAdicionales(AulaSinRecursosAdicionales aulaSinRecursosAdicionales) {
        this.aulaSinRecursosAdicionales = aulaSinRecursosAdicionales;
    }
    public AulaMultimedio getAulaMultimedio() {
        return this.aulaMultimedio;
    }
    
    public void setAulaMultimedio(AulaMultimedio aulaMultimedio) {
        this.aulaMultimedio = aulaMultimedio;
    }
    public Set getDiaReservaPeriodicas() {
        return this.diaReservaPeriodicas;
    }
    
    public void setDiaReservaPeriodicas(Set diaReservaPeriodicas) {
        this.diaReservaPeriodicas = diaReservaPeriodicas;
    }
    public AulaInformatica getAulaInformatica() {
        return this.aulaInformatica;
    }
    
    public void setAulaInformatica(AulaInformatica aulaInformatica) {
        this.aulaInformatica = aulaInformatica;
    }
    public Set getDiaReservaEsporadicas() {
        return this.diaReservaEsporadicas;
    }
    
    public void setDiaReservaEsporadicas(Set diaReservaEsporadicas) {
        this.diaReservaEsporadicas = diaReservaEsporadicas;
    }




}


