package Modelo;
// Generated 27/10/2017 22:11:40 by Hibernate Tools 4.3.1



/**
 * ClaveAdministrador generated by hbm2java
 */
public class ClaveAdministrador  implements java.io.Serializable {


     private ClaveAdministradorId id;
     private Administrador administrador;

    public ClaveAdministrador() {
    }

    public ClaveAdministrador(ClaveAdministradorId id, Administrador administrador) {
       this.id = id;
       this.administrador = administrador;
    }
   
    public ClaveAdministradorId getId() {
        return this.id;
    }
    
    public void setId(ClaveAdministradorId id) {
        this.id = id;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }




}


