package Modelo;
// Generated 26/10/2017 14:37:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ClaveAdministradorId generated by hbm2java
 */
public class ClaveAdministradorId  implements java.io.Serializable {


     private String valor;
     private Date fecha;
     private String administradorUsername;

    public ClaveAdministradorId() {
    }

    public ClaveAdministradorId(String valor, Date fecha, String administradorUsername) {
       this.valor = valor;
       this.fecha = fecha;
       this.administradorUsername = administradorUsername;
    }
   
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAdministradorUsername() {
        return this.administradorUsername;
    }
    
    public void setAdministradorUsername(String administradorUsername) {
        this.administradorUsername = administradorUsername;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClaveAdministradorId) ) return false;
		 ClaveAdministradorId castOther = ( ClaveAdministradorId ) other; 
         
		 return ( (this.getValor()==castOther.getValor()) || ( this.getValor()!=null && castOther.getValor()!=null && this.getValor().equals(castOther.getValor()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getAdministradorUsername()==castOther.getAdministradorUsername()) || ( this.getAdministradorUsername()!=null && castOther.getAdministradorUsername()!=null && this.getAdministradorUsername().equals(castOther.getAdministradorUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getValor() == null ? 0 : this.getValor().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getAdministradorUsername() == null ? 0 : this.getAdministradorUsername().hashCode() );
         return result;
   }   


}


