package Modelo;
// Generated 03/11/2017 15:18:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ClaveBedelId generated by hbm2java
 */
public class ClaveBedelId  implements java.io.Serializable {


     private String valor;
     private String bedelUsername;
     private Date fecha;

    public ClaveBedelId() {
    }

    public ClaveBedelId(String valor, String bedelUsername, Date fecha) {
       this.valor = valor;
       this.bedelUsername = bedelUsername;
       this.fecha = fecha;
    }
   
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getBedelUsername() {
        return this.bedelUsername;
    }
    
    public void setBedelUsername(String bedelUsername) {
        this.bedelUsername = bedelUsername;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClaveBedelId) ) return false;
		 ClaveBedelId castOther = ( ClaveBedelId ) other; 
         
		 return ( (this.getValor()==castOther.getValor()) || ( this.getValor()!=null && castOther.getValor()!=null && this.getValor().equals(castOther.getValor()) ) )
 && ( (this.getBedelUsername()==castOther.getBedelUsername()) || ( this.getBedelUsername()!=null && castOther.getBedelUsername()!=null && this.getBedelUsername().equals(castOther.getBedelUsername()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getValor() == null ? 0 : this.getValor().hashCode() );
         result = 37 * result + ( getBedelUsername() == null ? 0 : this.getBedelUsername().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


