package Modelo;
// Generated 03/11/2017 21:00:49 by Hibernate Tools 4.3.1



/**
 * DiaReservaPeriodica generated by hbm2java
 */
public class DiaReservaPeriodica  implements java.io.Serializable {


     private DiaReservaPeriodicaId id;
     private Aula aula;
     private ReservaPeriodica reservaPeriodica;
     private DiaSemana dia;
     private int anio;

    public DiaReservaPeriodica() {
    }

    public DiaReservaPeriodica(DiaReservaPeriodicaId id, Aula aula, ReservaPeriodica reservaPeriodica, DiaSemana dia, int anio) {
       this.id = id;
       this.aula = aula;
       this.reservaPeriodica = reservaPeriodica;
       this.dia = dia;
       this.anio = anio;
    }

    public int getAnio() {
        return anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }

    public DiaSemana getDia() {
        return dia;
    }

    public void setDia(DiaSemana dia) {
        this.dia = dia;
    }
   
    public DiaReservaPeriodicaId getId() {
        return this.id;
    }
    
    public void setId(DiaReservaPeriodicaId id) {
        this.id = id;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public ReservaPeriodica getReservaPeriodica() {
        return this.reservaPeriodica;
    }
    
    public void setReservaPeriodica(ReservaPeriodica reservaPeriodica) {
        this.reservaPeriodica = reservaPeriodica;
    }




}


