package Modelo;
// Generated 03/11/2017 21:00:49 by Hibernate Tools 4.3.1



/**
 * DiaReservaEsporadica generated by hbm2java
 */
public class DiaReservaEsporadica  implements java.io.Serializable {


     private DiaReservaEsporadicaId id;
     private Aula aula;//
     private ReservaEsporadica reservaEsporadica;

    public DiaReservaEsporadica() {
    }

    public DiaReservaEsporadica(DiaReservaEsporadicaId id, Aula aula, ReservaEsporadica reservaEsporadica) {
       this.id = id;
       this.aula = aula;
       this.reservaEsporadica = reservaEsporadica;
    }
   
    public DiaReservaEsporadicaId getId() {
        return this.id;
    }
    
    public void setId(DiaReservaEsporadicaId id) {
        this.id = id;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public ReservaEsporadica getReservaEsporadica() {
        return this.reservaEsporadica;
    }
    
    public void setReservaEsporadica(ReservaEsporadica reservaEsporadica) {
        this.reservaEsporadica = reservaEsporadica;
    }




}


