package Modelo;
// Generated 03/11/2017 15:18:41 by Hibernate Tools 4.3.1



/**
 * DocenteId generated by hbm2java
 */
public class DocenteId  implements java.io.Serializable {


     private int dni;
     private String apellido;

    public DocenteId() {
    }

    public DocenteId(int dni, String apellido) {
       this.dni = dni;
       this.apellido = apellido;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocenteId) ) return false;
		 DocenteId castOther = ( DocenteId ) other; 
         
		 return (this.getDni()==castOther.getDni())
 && ( (this.getApellido()==castOther.getApellido()) || ( this.getApellido()!=null && castOther.getApellido()!=null && this.getApellido().equals(castOther.getApellido()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDni();
         result = 37 * result + ( getApellido() == null ? 0 : this.getApellido().hashCode() );
         return result;
   }   


}


